### ISSUE TITLE
Identify common use cases that this standard should address

### ISSUE THREAD

**Issue by blesh** [Reactive-Streams-Open-Standard/reactive-streams-spec#1]
We need to identify the basic use-cases that need to be met to provide consumers of reactive streams libraries a consistent, but minimal, API.

**Comment by raimohanska** [comment]
Ship 'em in!

**Comment by blesh** [comment]
:+1:

**Comment by briancavalier** [comment]
This is certainly related the scope/goals thread on twitter today.  Do we need a new issue to focus specifically on those?  For example, "interop" and "interchange" were both mentioned.  Promises/A+ was, imho, successful in part because it focused so narrowly on interop.  Interchange likely has more surface area.

**Comment by blesh** [comment]
Moving this discussion to https://github.com/reactive-streams/reactive-streams-js/issues/2
